# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Define the  VM
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "ubuntu/bionic64"
    gitlab.vm.hostname = "gitlab"
    gitlab.vm.network "private_network", ip:"192.168.33.10"
    gitlab.vm.disk :disk, size: "20GB", primary: true
    gitlab.vm.provider "virtualbox" do |vb|
      vb.memory = "8096"
      vb.cpus = 2
    end

    gitlab.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update

      # install docker & docker-compose
      apt-get install -y docker.io docker-compose
      # install gitlab: https://about.gitlab.com/install/#ubuntu
      apt-get install -y curl openssh-server ca-certificates tzdata perl
      curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
      sudo EXTERNAL_URL="http://gitlab.localdomain" apt-get install gitlab-ee
      # pull some images in advance
      docker pull gitlab/gitlab-runner:latest
      docker pull sonarsource/sonar-scanner-cli:latest
      docker pull golang:1.17
      docker pull docker:latest
      # set sysctl for sonarqube
      sysctl vm.max_map_count=262144
      # run sonarqube
      # cd /vagrant && docker-compose up -d
      # add some records to /etc/hosts
      echo -e "192.168.33.10\tubuntu-bionic\tubuntu-bionic" >> /etc/hosts
      echo -e "192.168.33.10\tgitlab.localdomain\tgitlab" >> /etc/hosts
    SHELL
  end
  
  #config.vm.box = "ubuntu/bionic64"
  #config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.disk :disk, size: "15GB", primary: true
  ##
  #config.vm.provider "virtualbox" do |vb|
  #  vb.memory = "6144"
  #end

  # Define the runner VM
  config.vm.define "runner" do |runner|
    runner.vm.box = "ubuntu/bionic64"
    runner.vm.hostname = "runner"
    runner.vm.network "private_network", ip:"192.168.33.11"
    runner.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
  end  
end
